spring:
  application:
    name: classroom-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ''
    url: jdbc:mysql://localhost:3306/classroom
    username: root

  config:
    import: "optional:configserver:http://localhost:8088"