server:
  port: 8090
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    gateway:
      routes:
        - id: classroom-service
          uri: lb://classroom-service
          predicates:
            - Path=/classroom/**
          filters:
            - AuthenticationFilter
        - id: reservation-service
          uri: lb://reservation-service
          predicates:
            - Path=/api/v1/reservations/**
          filters:
            - AuthenticationFilter
        - id: identity-service
          uri: lb://identity-service
          predicates:
            - Path=/auth/**
#Actuator prometheus endpoint
management:
  endpoints:
    web:
      exposure:
        include: prometheus
  tracing:
    sampling:
      probability: 1.0
secrets:
  jwt: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437