server:
  port: 8090
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    gateway:
      routes:
        - id: classroom-service
          uri: lb://classroom-service
          predicates:
            - Path=/classroom/**
          filters:
            - AuthenticationFilter
        - id: reservation-service
          uri: lb://reservation-service
          predicates:
            - Path=/api/v1/reservations/**
          filters:
            - AuthenticationFilter
        - id: identity-service
          uri: lb://identity-service
          predicates:
            - Path=/auth/**

management:
  tracing:
    sampling:
      probability: 1.0